In [1]:
import sys
import numpy as np

Basic Numpy Arrays

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])

In [6]:
b= np.array([0, .5, 1, 1.5, 2])

In [7]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:3]

array([2, 3])

In [11]:
a[1:-1]

array([2, 3])

In [12]:
a[::2]

array([1, 3])

In [13]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [14]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [16]:
2**5

32

Array Types 

In [17]:
a

array([1, 2, 3, 4])

In [18]:
a.dtype

dtype('int64')

In [19]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

b.dtype

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype=np.float64)
print(arr)

[1. 2. 3. 4.]


In [26]:
c= np.array(['a', 'b', 'c'])

In [27]:
c.dtype

dtype('<U1')

In [28]:
d=np.array([{'a': 1}, sys])

In [29]:
d.dtype

dtype('O')

Dimensions and shapes

In [30]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [31]:
A.shape

(2, 3)

In [32]:
A.ndim

2

In [33]:
A.size

6

In [35]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [36]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [37]:
B.shape

(2, 2, 3)

In [39]:
B.ndim

3

In [40]:
B.size

12

In [43]:
import numpy as np

c = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
], dtype=object) # Explicitly set dtype to object

print(c)
print(c.shape) # Output: (2,) - This tells you it's a 1D array of 2 objects
print(c[0])    # Accesses the first object (a list of lists or an array)
print(c[1])    # Accesses the second object (a list of lists or an array)

[list([[12, 11, 10], [9, 8, 7]]) list([[6, 5, 4]])]
(2,)
[[12, 11, 10], [9, 8, 7]]
[[6, 5, 4]]


In [44]:
c.dtype

dtype('O')

In [46]:
c.shape

(2,)

In [47]:
c.size

2

In [48]:
type(c[0])

list

Indexing and Slicing of Matrices

In [49]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [50]:
A[1]

array([4, 5, 6])

In [51]:
A[1] [0]

np.int64(4)

In [52]:
A[1,0]

np.int64(4)

In [53]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [56]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [57]:
A[:2, 2:]

array([[3],
       [6]])

In [58]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10.10,10])

In [59]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
A[2] = 99

In [62]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

Summary statistics

In [63]:
a = np.array([1, 2,3, 4])

In [64]:
a.sum()

np.int64(10)

In [65]:
a.mean()

np.float64(2.5)

In [66]:
a.std()

np.float64(1.118033988749895)

In [67]:
a.var()

np.float64(1.25)

In [68]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [69]:
A.sum()

np.int64(45)

In [70]:
A.mean()

np.float64(5.0)

In [71]:
A.std()

np.float64(2.581988897471611)

In [72]:
A.sum(axis=0)

array([12, 15, 18])

In [73]:
A.sum(axis=1)

array([ 6, 15, 24])

In [74]:
A.mean(axis=0)

array([4., 5., 6.])

In [75]:
A.mean(axis=1)

array([2., 5., 8.])

In [76]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [77]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Brodcasting And Vectorized operations

In [11]:
import sys
import numpy as np

In [12]:
a = np.arange(4)

In [13]:
a

array([0, 1, 2, 3])

In [14]:
a + 10

array([10, 11, 12, 13])

In [15]:
a - 10

array([-10,  -9,  -8,  -7])

In [16]:
a * 10

array([ 0, 10, 20, 30])

In [17]:
a

array([0, 1, 2, 3])

In [18]:
a +=10

In [19]:
a

array([10, 11, 12, 13])

In [22]:
a += 100

In [23]:
a

array([310, 311, 312, 313])

In [24]:
l = [0, 1, 2, 3]

In [26]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [27]:
a = np.arange(4)

In [28]:
a

array([0, 1, 2, 3])

In [36]:
b = np.array([10, 10, 10 ,10])

In [37]:
b

array([10, 10, 10, 10])

In [38]:
a + b

array([210, 211, 212, 213])

In [39]:
a * b

array([2000, 2010, 2020, 2030])

In [30]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
a + 10

array([10, 11, 12, 13])

In [32]:
a * 10

array([ 0, 10, 20, 30])

In [34]:
a += 100

In [35]:
a

array([200, 201, 202, 203])

In [41]:
a = np.arange(5)

In [42]:
a + 20

array([20, 21, 22, 23, 24])

In [43]:
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]


LINEAR ALGEBRA

In [50]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [52]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [53]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [54]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [55]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [56]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

SIZE OF OBJECTS IN MEMORY

Int, floats

In [58]:
#An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [59]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [60]:
#Numpy size is much smaller
np.dtype(int).itemsize

8

In [61]:
np.dtype(float).itemsize

8

LIST ARE EVEN LARGER

In [63]:
# A one-element list
sys.getsizeof([1])

64

In [64]:
# An array of one element in numpy 
np.array([1]).nbytes

8

AND PERFORMANCE IS ALSO IMPORTANT

In [65]:
l = list(range(1000))

In [66]:
a = np.arange(1000)

In [67]:
%time np.sum(a **2)

CPU times: total: 0 ns
Wall time: 8.95 ms


np.int64(332833500)

In [68]:
%time sum([x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 4.68 ms


332833500

USEFUL NUMFY FUNCTIONS

random

In [69]:
np.random.random(size=2)

array([0.04754837, 0.09116219])

In [70]:
np.random.normal(size=2)

array([ 0.19688423, -0.81059139])

In [71]:
np.random.rand(2,4)

array([[0.93254726, 0.68142854, 0.60824464, 0.9660328 ],
       [0.6555068 , 0.52267923, 0.23200651, 0.90671546]])

arange

In [72]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [74]:
np. arange(0, 1, 1)

array([0])

reshape

In [75]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

LINSPACE

In [76]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [77]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [78]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

Zeros, Ones, empty

In [79]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [85]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
arr = np.zeros((3, 3), dtype=np.int64)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [92]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [94]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [96]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

Identity and eye

In [97]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [104]:
"Hello World"[6]

'W'